drawstyle:
  alpha: 1.0
  fillcolor: '#ffffff'
  height: 1.0
  linecolor: '#000000'
  linewidth: 0.5
  stride: 1.0
  zorder: 5
elements:
  ' ':
    label: Loop
    primitives:
    - LinePrimitive-9ca501
  '-':
    label: Loop
    primitives:
    - LinePrimitive-9ca501
  B:
    label: $\beta$-Bridge
    primitives:
    - ArrowPrimitive-3783fb
  C:
    label: Loop
    primitives:
    - LinePrimitive-9ca501
  E:
    label: Extended $\beta$-Strand
    primitives:
    - ArrowPrimitive-dadbeb
  G:
    label: $3_{10}$-Helix
    primitives:
    - HelixPrimitive-2d479c
    - HelixPrimitive-2d043b
  H:
    label: $\alpha$-Helix
    primitives:
    - HelixPrimitive-5daeb8
    - HelixPrimitive-740af3
  I:
    label: $\pi$-Helix
    primitives:
    - HelixPrimitive-2f2cbe
    - HelixPrimitive-4852a1
  P:
    label: $\kappa$-Helix
    primitives:
    - HelixPrimitive-8258c9
    - HelixPrimitive-df63f7
  S:
    label: Bend
    primitives:
    - LinePrimitive-825a32
  T:
    label: H-bonded turn
    primitives:
    - LinePrimitive-0f3300
  b:
    label: $\beta$-Bridge
    primitives:
    - ArrowPrimitive-3783fb
  c:
    label: Loop
    primitives:
    - LinePrimitive-9ca501
  e:
    label: Extended $\beta$-Strand
    primitives:
    - ArrowPrimitive-dadbeb
  g:
    label: $3_{10}$-Helix
    primitives:
    - HelixPrimitive-2d479c
    - HelixPrimitive-2d043b
  h:
    label: $\alpha$-Helix
    primitives:
    - HelixPrimitive-5daeb8
    - HelixPrimitive-740af3
  i:
    label: $\pi$-Helix
    primitives:
    - HelixPrimitive-2f2cbe
    - HelixPrimitive-4852a1
  p:
    label: $\kappa$-Helix
    primitives:
    - HelixPrimitive-8258c9
    - HelixPrimitive-df63f7
  s:
    label: Bend
    primitives:
    - LinePrimitive-825a32
  t:
    label: H-bonded turn
    primitives:
    - LinePrimitive-0f3300
primitives:
  ArrowPrimitive-3783fb:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor: '#74bbf9'
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor: '#191921'
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  ArrowPrimitive-dadbeb:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor: '#4c82c7'
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor: '#191921'
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-2d043b:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#edb7d6'
    height_scalar: 0.7
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-2d479c:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#e33e9e'
    height_scalar: 0.7
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-2f2cbe:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#9343b3'
    height_scalar: 1.0
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 4.1
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-4852a1:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#cda9db'
    height_scalar: 1.0
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 4.1
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-5daeb8:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#d94740'
    height_scalar: 0.9
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-740af3:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#eebbbb'
    height_scalar: 0.9
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-8258c9:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#fdb71f'
    height_scalar: 0.5
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-df63f7:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#f1deb4'
    height_scalar: 0.5
    linecolor: '#191921'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  LinePrimitive-0f3300:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#09967A'
    linewidth_scalar: 5
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-825a32:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#5fcb5b'
    linewidth_scalar: 5
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-9ca501:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#191921'
    linewidth_scalar: 1
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
