drawstyle:
  alpha: 1.0
  fillcolor: '#ffffff'
  height: 1.0
  linecolor: '#000000'
  linewidth: 0.5
  stride: 1.0
  zorder: 5
elements:
  ' ':
    label: Loop
    primitives:
    - LinePrimitive-2e3bc2
  '-':
    label: Loop
    primitives:
    - LinePrimitive-2e3bc2
  B:
    label: $\beta$-Bridge
    primitives:
    - ArrowPrimitive-c97f22
  C:
    label: Loop
    primitives:
    - LinePrimitive-2e3bc2
  E:
    label: Extended $\beta$-Strand
    primitives:
    - ArrowPrimitive-b8aa62
  G:
    label: $3_{10}$-Helix
    primitives:
    - HelixPrimitive-873f8c
    - HelixPrimitive-fc3883
  H:
    label: $\alpha$-Helix
    primitives:
    - HelixPrimitive-1ef1c3
    - HelixPrimitive-d14ba2
  I:
    label: $\pi$-Helix
    primitives:
    - HelixPrimitive-2a394d
    - HelixPrimitive-3c694f
  P:
    label: $\kappa$-Helix
    primitives:
    - HelixPrimitive-42efe2
    - HelixPrimitive-4b7fef
  S:
    label: Bend
    primitives:
    - LinePrimitive-4d4940
  T:
    label: H-bonded turn
    primitives:
    - LinePrimitive-635be3
  b:
    label: $\beta$-Bridge
    primitives:
    - ArrowPrimitive-c97f22
  c:
    label: Loop
    primitives:
    - LinePrimitive-2e3bc2
  e:
    label: Extended $\beta$-Strand
    primitives:
    - ArrowPrimitive-b8aa62
  g:
    label: $3_{10}$-Helix
    primitives:
    - HelixPrimitive-873f8c
    - HelixPrimitive-fc3883
  h:
    label: $\alpha$-Helix
    primitives:
    - HelixPrimitive-1ef1c3
    - HelixPrimitive-d14ba2
  i:
    label: $\pi$-Helix
    primitives:
    - HelixPrimitive-2a394d
    - HelixPrimitive-3c694f
  p:
    label: $\kappa$-Helix
    primitives:
    - HelixPrimitive-42efe2
    - HelixPrimitive-4b7fef
  s:
    label: Bend
    primitives:
    - LinePrimitive-4d4940
  t:
    label: H-bonded turn
    primitives:
    - LinePrimitive-635be3
primitives:
  ArrowPrimitive-b8aa62:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor: '#ccddbb'
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor: '#111111'
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  ArrowPrimitive-c97f22:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor: '#ccaadd'
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor: '#111111'
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-1ef1c3:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#8888cc'
    height_scalar: 0.9
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-2a394d:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#dd5588'
    height_scalar: 1.0
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 4.1
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-3c694f:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#eebbcc'
    height_scalar: 1.0
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 4.1
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-42efe2:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#ffbb22'
    height_scalar: 0.5
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-4b7fef:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#ffddbb'
    height_scalar: 0.5
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-873f8c:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor: '#66ccee'
    height_scalar: 0.7
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-d14ba2:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#ccccee'
    height_scalar: 0.9
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  HelixPrimitive-fc3883:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor: '#bbeeee'
    height_scalar: 0.7
    linecolor: '#111111'
    linewidth_scalar: 1.0
    ribbon_period: 3.0
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.5
  LinePrimitive-2e3bc2:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#111111'
    linewidth_scalar: 1
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-4d4940:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#eecc66'
    linewidth_scalar: 5
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-635be3:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor: '#aaaaaa'
    linewidth_scalar: 5
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
