drawstyle:
  alpha: 1.0
  fillcolor: '#ffffff'
  height: 1.0
  linecolor: '#000000'
  linewidth: 0.7
  stride: 1.0
  zorder: 5
elements:
  ' ':
    label: Loop
    primitives:
    - LinePrimitive-138733
  '-':
    label: Loop
    primitives:
    - LinePrimitive-138733
  H:
    label: Helix
    primitives:
    - HelixPrimitive-0f311d
    - HelixPrimitive-eba8e2
  L:
    label: Loop
    primitives:
    - LinePrimitive-138733
  S:
    label: Sheet
    primitives:
    - ArrowPrimitive-9a2175
  h:
    label: Helix
    primitives:
    - HelixPrimitive-0f311d
    - HelixPrimitive-eba8e2
  l:
    label: Loop
    primitives:
    - LinePrimitive-138733
  s:
    label: Sheet
    primitives:
    - ArrowPrimitive-9a2175
primitives:
  ArrowPrimitive-9a2175:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor:
    - 1.0
    - 0.0
    - 0.0
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-0f311d:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor:
    - 0.0
    - 1.0
    - 1.0
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-eba8e2:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor:
    - 0.0
    - 0.8
    - 0.8
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-138733:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor:
    - 1.0
    - 0
    - 1.0
    linewidth_scalar: 2
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
