drawstyle:
  alpha: 1.0
  fillcolor: '#ffffff'
  height: 1.0
  linecolor: '#000000'
  linewidth: 0.7
  stride: 1.0
  zorder: 5
elements:
  ' ':
    label: Loop
    primitives:
    - LinePrimitive-f8f2eb
  '-':
    label: Loop
    primitives:
    - LinePrimitive-f8f2eb
  H:
    label: Helix
    primitives:
    - HelixPrimitive-12f2d2
    - HelixPrimitive-7709fc
  L:
    label: Loop
    primitives:
    - LinePrimitive-f8f2eb
  S:
    label: Sheet
    primitives:
    - ArrowPrimitive-5e0a11
  h:
    label: Helix
    primitives:
    - HelixPrimitive-12f2d2
    - HelixPrimitive-7709fc
  l:
    label: Loop
    primitives:
    - LinePrimitive-f8f2eb
  s:
    label: Sheet
    primitives:
    - ArrowPrimitive-5e0a11
primitives:
  ArrowPrimitive-5e0a11:
    alpha_scalar: 1.0
    arrow_tip_length: 3
    fillcolor:
    - 1.0
    - 1.0
    - 0.0
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-12f2d2:
    alpha_scalar: 1.0
    fill_inner_ribbon: false
    fillcolor:
    - 1.0
    - 0.0
    - 0.0
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 0.0
  HelixPrimitive-7709fc:
    alpha_scalar: 1.0
    fill_inner_ribbon: true
    fillcolor:
    - 0.6
    - 0.0
    - 0.0
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  LinePrimitive-f8f2eb:
    alpha_scalar: 1.0
    fillcolor: null
    height_scalar: 1.0
    linecolor:
    - 0.0
    - 1.0
    - 0.0
    linewidth_scalar: 2
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
